name: Auto Release

on:
  repository_dispatch:
    types: release
  release:
    types: [published]
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Login to github registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }}
    - name: Login to docker-hub registry
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_IO_USER }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    - name: Execute Release
      id: release
      run: |
        . ./release.sh ghcr.io/${{ github.repository_owner }}/humhub docker.io/${{ vars.DOCKER_IO_USER }}/humhub
